name: Deploy to DigitalOcean Registry

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
         token: ${{ secrets.DO_API_KEY }}
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to DigitalOcean Container Registry
        run: |
          doctl registry login
        env:
          DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.DO_API_KEY }}

      - name: Build and tag Docker image
        run: docker build -t registry.digitalocean.com/${{ secrets.REGISTRY_NAME }}/split-smart:latest .

      - name: Push Docker image to DigitalOcean Registry
        run: docker push registry.digitalocean.com/${{ secrets.REGISTRY_NAME }}/split-smart:latest

      - name: Run Garbage Collection
        run: doctl registry garbage-collection start [--include-untagged-manifests] [${{ secrets.REGISTRY_NAME }}]

